#!/usr/bin/env bash
##########################################################################
# If not stated otherwise in this file or this component's LICENSE
# file the following copyright and licenses apply:
#
# Copyright 2014 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################

TOP_DIR=$(pwd)

# Call the meta-rdk setup script.
source meta-rdk/setup-environment $1
if [ $? -ne 0 ]; then
    return 1
fi

# Add meta-cmf-broadband only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-broadband[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-broadband ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-broadband"
EOF
fi

# Add meta-cmf-broadband only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf-mesh[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf-mesh ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf-mesh"
EOF
fi

# Add meta-cmf only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-cmf[^-]') -eq 0 -a -d  $TOP_DIR/meta-cmf ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-cmf"
EOF
fi

# Add meta-rdk-voice-sdk only if not already present.
if [ $(grep '^BBLAYERS' conf/bblayers.conf | grep -c 'meta-rdk-ext') -eq 0 -a -d  $TOP_DIR/meta-rdk-ext ]
then
    cat >> conf/bblayers.conf <<EOF
BBLAYERS =+ "\${RDKROOT}/meta-rdk-ext"
EOF
fi

#for capturing the timestamp
CPC_CUSTOM_STAMP=`/bin/date -u +%Y%m%d%H%M%S`
echo 'CPC_CUSTOM_STAMP = "'${CPC_CUSTOM_STAMP}'"' >> conf/auto.conf
